// Generated by CoffeeScript 1.8.0
(function() {
  var costPerGallon, date, fuelType, numberOfGallons, stationLocation, stationName, totalCost;

  numberOfGallons = 13.000;

  costPerGallon = 2.05;

  totalCost = numberOfGallons * costPerGallon;

  stationName = "Chevron";

  stationLocation = "Peoria";

  fuelType = "unleaded";

  date = new Date().toDateString();

  console.log("\n\n-= Thank you for shopping at %s (%s) =-", stationName, stationLocation);

  console.log(date);

  console.log("Fuel type: " + fuelType);

  console.log("%d gallons x %d = $%d\n\n", numberOfGallons, costPerGallon, totalCost);

}).call(this);
